version: '2'
services:
    mijitest99-app:
        image: mijitest99
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://mijitest99-postgresql:5432/mijitest99
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    mijitest99-postgresql:
        extends:
            file: postgresql.yml
            service: mijitest99-postgresql
