version: '2'
services:
    mijitest99-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/mijitest99/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=mijitest99
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
